-- ============================================================
-- SciLab 7th Grade — Supabase Schema
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard)
-- ============================================================

-- 1) Student scores / state
create table if not exists public.sciencelab_scores (
  id bigint generated by default as identity primary key,
  student_name text not null,
  section text,                          -- 'blue' | 'red' | 'teacher'
  xp integer default 0,
  total_xp integer default 0,
  level integer default 1,
  streak integer default 0,
  answered integer default 0,
  correct integer default 0,
  accuracy numeric generated always as (
    case when answered > 0 then round(correct::numeric / answered * 100, 1) else 0 end
  ) stored,
  exam_score numeric,
  best_exam_score numeric,
  badges text[] default '{}',
  mastery jsonb default '{}',
  skill_lvl jsonb default '{}',
  card_box jsonb default '{}',
  updated_at timestamptz default now(),
  created_at timestamptz default now()
);
create unique index if not exists sciencelab_scores_name_key on public.sciencelab_scores (student_name);

-- 2) AI help / intervention logs
create table if not exists public.sciencelab_interventions (
  id bigint generated by default as identity primary key,
  student_name text,
  section text,
  skill text,
  confusion text,
  response text,
  level integer,
  created_at timestamptz default now()
);

-- 3) Teacher notices (message broadcast)
create table if not exists public.sciencelab_notices (
  id bigint generated by default as identity primary key,
  message text,
  active boolean default true,
  created_at timestamptz default now()
);

-- 4) Notice read receipts
create table if not exists public.sciencelab_notice_reads (
  id bigint generated by default as identity primary key,
  notice_id bigint references public.sciencelab_notices(id) on delete cascade,
  student_name text,
  section text,
  read_at timestamptz default now()
);

-- Row Level Security: allow anonymous read/write for the class app.
alter table public.sciencelab_scores enable row level security;
alter table public.sciencelab_interventions enable row level security;
alter table public.sciencelab_notices enable row level security;
alter table public.sciencelab_notice_reads enable row level security;

create policy "anon read scores" on public.sciencelab_scores for select using (true);
create policy "anon upsert scores" on public.sciencelab_scores for insert with check (true);
create policy "anon update scores" on public.sciencelab_scores for update using (true);
create policy "anon read interventions" on public.sciencelab_interventions for select using (true);
create policy "anon insert interventions" on public.sciencelab_interventions for insert with check (true);
create policy "anon read notices" on public.sciencelab_notices for select using (true);
create policy "anon insert notices" on public.sciencelab_notices for insert with check (true);
create policy "anon update notices" on public.sciencelab_notices for update using (true);
create policy "anon read reads" on public.sciencelab_notice_reads for select using (true);
create policy "anon insert reads" on public.sciencelab_notice_reads for insert with check (true);

-- Optional: realtime for the teacher dashboard live updates
alter publication supabase_realtime add table public.sciencelab_scores;
alter publication supabase_realtime add table public.sciencelab_interventions;