// Server-side authoritative item bank (mirror of index.html ITEMS).
// Used by scienceVerifyAnswer for full anti-cheat.
module.exports = [

  /* Photosynthesis Process */
  {"sk":"photo-process","type":"mc","q":"Photosynthesis is the process plants use to make their own ___ .","o":["water","food","soil","air"],"a":1,"fb":"Photosynthesis makes <b>food</b> (glucose) — plants are producers!","hint":"Plants don't hunt or shop — they make it themselves."},
  {"sk":"photo-process","type":"mc","q":"Where does photosynthesis mainly happen?","o":["In the roots","In the leaves","In the flowers","In the trunk"],"a":1,"fb":"Photosynthesis happens mainly in the <b>leaves</b>, where chlorophyll captures sunlight.","hint":"The green parts of the plant do the work."},
  {"sk":"photo-process","type":"mc","q":"What is the correct order of the photosynthesis process?","o":["Sunlight → leaves use water & CO₂ → glucose + oxygen","Glucose → sunlight → water","Oxygen → water → glucose","Soil → roots → leaves"],"a":0,"fb":"Sunlight + water + CO₂ → <b>glucose + oxygen</b> in the leaves.","hint":"Think of sunlight as the energy source at the start."},
  {"sk":"photo-process","type":"fill","q":"Plants capture energy from the sun through the process called ___.","a":"photosynthesis","fb":"The process is called <b>photosynthesis</b> — photo (light) + synthesis (making).","hint":"'Photo' means light."},
  {"sk":"photo-process","type":"mc","q":"What happens to plants at night (no sunlight)?","o":["They stop living","They cannot photosynthesize, so they use stored glucose","They turn red","They make more oxygen"],"a":1,"fb":"Without sunlight plants <b>cannot photosynthesize</b>; they use stored glucose for energy.","hint":"Energy has to come from somewhere."},
  /* What Plants Eat (Inputs) */
  {"sk":"photo-inputs","type":"mc","q":"Which of these is NOT an input for photosynthesis?","o":["Sunlight","Carbon dioxide","Water","Oxygen"],"a":3,"fb":"<b>Oxygen</b> is an OUTPUT (product), not an input! Inputs are sunlight, water and CO₂.","hint":"Oxygen is what plants give away."},
  {"sk":"photo-inputs","type":"mc","q":"Where do plants get the water they need for photosynthesis?","o":["From the air","From the soil through their roots","From other plants","From rain only"],"a":1,"fb":"Roots absorb water from the <b>soil</b>.","hint":"Roots act like straws."},
  {"sk":"photo-inputs","type":"mc","q":"Plants take in carbon dioxide mainly through their ___ .","o":["roots","flowers","leaves (stomata)","fruits"],"a":2,"fb":"CO₂ enters through tiny pores called <b>stomata</b> on the leaves.","hint":"Tiny doorways on the leaf surface."},
  {"sk":"photo-inputs","type":"fill","q":"The three things plants need for photosynthesis are sunlight, water and ___.","a":"carbon dioxide","fb":"Sunlight + water + <b>carbon dioxide</b> = food for plants.","hint":"It's the gas we breathe OUT."},
  {"sk":"photo-inputs","type":"mc","q":"What would happen if a plant gets no sunlight for a long time?","o":["It grows faster","It cannot make food and may weaken or die","It makes more chlorophyll","It turns blue"],"a":1,"fb":"Without sunlight a plant <b>cannot make food</b> and eventually weakens.","hint":"Sunlight is the engine!"},
  /* Plant Food & Products */
  {"sk":"photo-outputs","type":"mc","q":"What is the main food plants make during photosynthesis?","o":["Starch only","Glucose (a sugar)","Protein","Oxygen"],"a":1,"fb":"The food is <b>glucose</b>, a simple sugar that plants use for energy and growth.","hint":"Sweet result of photosynthesis."},
  {"sk":"photo-outputs","type":"mc","q":"Which gas do plants RELEASE during photosynthesis?","o":["Carbon dioxide","Nitrogen","Oxygen","Hydrogen"],"a":2,"fb":"Plants release <b>oxygen</b> — the air we breathe!","hint":"Think about what YOU breathe in."},
  {"sk":"photo-outputs","type":"mc","q":"Plants store extra glucose as ___ .","o":["Water","Starch","Salt","Sap"],"a":1,"fb":"Extra glucose is stored as <b>starch</b> in roots, stems and seeds.","hint":"Potatoes are full of it!"},
  {"sk":"photo-outputs","type":"fill","q":"Photosynthesis produces glucose and ___, which we need to breathe.","a":"oxygen","fb":"The two products are <b>glucose</b> and <b>oxygen</b>.","hint":"It starts with 'ox'."},
  {"sk":"photo-outputs","type":"mc","q":"Why is photosynthesis important for ALL living things?","o":["It makes oxygen and food for the food chain","It makes rain","It cleans the soil","It cools the earth"],"a":0,"fb":"Photosynthesis produces <b>oxygen</b> and is the <b>base of the food chain</b> — all life depends on it.","hint":"Where does the oxygen you breathe come from?"},
  /* Chlorophyll & Leaves */
  {"sk":"chlorophyll","type":"mc","q":"What makes leaves look green?","o":["Water","Chlorophyll","Soil","Sunlight"],"a":1,"fb":"<b>Chlorophyll</b> is the green pigment that captures sunlight.","hint":"It's inside chloroplasts."},
  {"sk":"chlorophyll","type":"mc","q":"Where is chlorophyll found inside plant cells?","o":["In the nucleus","In the chloroplasts","In the cell wall","In the vacuole"],"a":1,"fb":"Chlorophyll lives inside <b>chloroplasts</b>.","hint":"'Chloro-' + 'plast' — the green factory."},
  {"sk":"chlorophyll","type":"mc","q":"What happens to leaves in autumn when chlorophyll breaks down?","o":["They fall while still green","They change color (yellow, orange, red)","They turn black","They stop existing"],"a":1,"fb":"When <b>chlorophyll breaks down</b>, other pigments show — leaves turn yellow, orange and red.","hint":"The green paint fades and other colors appear."},
  {"sk":"chlorophyll","type":"fill","q":"The green pigment that captures sunlight in leaves is ___.","a":"chlorophyll","fb":"<b>Chlorophyll</b> captures light energy for photosynthesis.","hint":"Chloro + phyll (Greek for green leaf)."},
  {"sk":"chlorophyll","type":"mc","q":"Why do plants that stay in the dark lose their green color?","o":["They get too cold","They cannot produce chlorophyll without light","They lose their roots","They stop drinking water"],"a":1,"fb":"Without light, plants <b>cannot make chlorophyll</b>, so they become pale/yellow.","hint":"Light is needed to build the green pigment."},
  /* Stomata & Gas Exchange */
  {"sk":"stomata","type":"mc","q":"What are stomata?","o":["Tiny pores on leaves","Small roots","Flower petals","Seed coverings"],"a":0,"fb":"<b>Stomata</b> are tiny pores on the leaf surface that allow gas exchange.","hint":"Tiny mouths on the leaf."},
  {"sk":"stomata","type":"mc","q":"What enters and exits through the stomata?","o":["Water and glucose only","Carbon dioxide, oxygen and water vapor","Only sunlight","Only minerals"],"a":1,"fb":"Stomata let <b>CO₂ in</b>, <b>O₂ out</b>, and release <b>water vapor</b> (transpiration).","hint":"Small openings = small gas exchange."},
  {"sk":"stomata","type":"mc","q":"Each stoma is guarded by two ___ cells.","o":["guard","blood","root","stem"],"a":0,"fb":"Two <b>guard cells</b> open and close each stoma.","hint":"They open and close like a mouth."},
  {"sk":"stomata","type":"fill","q":"The tiny pores on leaves that allow gas exchange are called ___.","a":"stomata","fb":"<b>Stomata</b> — singular 'stoma' — let gases in and out.","hint":"'Stoma' means mouth in Greek."},
  {"sk":"stomata","type":"mc","q":"What is transpiration?","o":["Loss of water vapor through stomata","The color of leaves","A type of soil","The smell of flowers"],"a":0,"fb":"<b>Transpiration</b> is the loss of water vapor mainly through stomata.","hint":"Water evaporating from leaves."},
  /* Plant Respiration */
  {"sk":"plant-resp","type":"mc","q":"Respiration is the process cells use to release ___ from glucose.","o":["energy","color","water only","oxygen"],"a":0,"fb":"Respiration releases <b>energy</b> from glucose using oxygen.","hint":"It's how living things get power."},
  {"sk":"plant-resp","type":"mc","q":"What gases do plants take in and release during respiration?","o":["Take in O₂, release CO₂","Take in CO₂, release O₂","Take in N₂, release O₂","Take in water, release salt"],"a":0,"fb":"In <b>respiration</b> plants take in <b>O₂</b> and release <b>CO₂</b> (opposite of photosynthesis).","hint":"It's like how animals breathe."},
  {"sk":"plant-resp","type":"mc","q":"When do plants respire?","o":["Only at night","Only in the morning","All the time (day and night)","Never"],"a":2,"fb":"Plants respire <b>all the time</b> — they always need energy to live.","hint":"Living things never stop needing energy."},
  {"sk":"plant-resp","type":"fill","q":"The process that releases energy from glucose in plant cells is called ___.","a":"respiration","fb":"<b>Respiration</b> releases energy; photosynthesis stores it.","hint":"It starts with 'resp'."},
  {"sk":"plant-resp","type":"mc","q":"What is the main difference between photosynthesis and respiration?","o":["Photosynthesis stores energy; respiration releases it","They are identical","Respiration stores energy; photosynthesis releases it","Both release oxygen"],"a":0,"fb":"<b>Photosynthesis stores energy</b> (makes food); <b>respiration releases energy</b> (uses food).","hint":"One builds up, the other breaks down."},
  /* Root Respiration */
  {"sk":"root-resp","type":"mc","q":"How do roots get the oxygen they need?","o":["From the soil air spaces","From the flowers","From the sun","From the fruits"],"a":0,"fb":"Roots take oxygen from <b>air spaces in the soil</b>.","hint":"That's why soil must be loose, not packed."},
  {"sk":"root-resp","type":"mc","q":"Why is it bad to over-water a plant?","o":["Water fills the air spaces, so roots can't get oxygen","Water is too heavy","Water attracts bugs only","It makes leaves fall"],"a":0,"fb":"Too much water <b>fills the air spaces</b> in soil and roots can't breathe → root rot.","hint":"Roots need air, not just water."},
  {"sk":"root-resp","type":"mc","q":"What happens to roots that cannot get oxygen?","o":["They grow faster","They cannot release energy and may rot or die","They turn green","They produce fruit"],"a":1,"fb":"Without oxygen, roots <b>cannot respire</b> and may rot.","hint":"No air = no energy."},
  {"sk":"root-resp","type":"fill","q":"Roots breathe by absorbing ___ from the spaces between soil particles.","a":"oxygen","fb":"Roots absorb <b>oxygen</b> from soil air spaces for respiration.","hint":"It's a gas that fills the tiny gaps in soil."},
  {"sk":"root-resp","type":"mc","q":"Which soil is best for plant roots to breathe?","o":["Hard, packed clay","Soft, loose, well-aerated soil","Pure sand only","Puddle-filled mud"],"a":1,"fb":"<b>Loose, well-aerated soil</b> has air spaces so roots can breathe.","hint":"Roots need air pockets."},
  /* Respiratory Organs */
  {"sk":"human-organs","type":"mc","q":"What is the correct order of the air pathway in humans?","o":["Nose → trachea → bronchi → lungs","Lungs → nose → trachea","Trachea → nose → lungs","Bronchi → trachea → nose"],"a":0,"fb":"Air goes: <b>nose → trachea (windpipe) → bronchi → lungs</b>.","hint":"Start where you breathe in."},
  {"sk":"human-organs","type":"mc","q":"The trachea is also known as the ___ .","o":["windpipe","esophagus","stomach tube","voice box"],"a":0,"fb":"The <b>trachea</b> is the windpipe carrying air to the lungs.","hint":"Air tube, not food tube."},
  {"sk":"human-organs","type":"mc","q":"What do the bronchi do?","o":["Carry air into each lung","Pump blood","Digest food","Make sound"],"a":0,"fb":"The <b>bronchi</b> carry air from the trachea into each lung.","hint":"Two branches, one per lung."},
  {"sk":"human-organs","type":"fill","q":"The two spongy organs in the chest where gas exchange happens are the ___.","a":"lungs","fb":"The <b>lungs</b> are the main organs of the respiratory system.","hint":"You have two of them."},
  {"sk":"human-organs","type":"mc","q":"Where is the trachea located?","o":["In the neck/throat, in front of the esophagus","Inside the brain","In the stomach","In the legs"],"a":0,"fb":"The <b>trachea</b> runs down the front of the neck, in front of the esophagus.","hint":"You can feel it at the front of your throat."},
  /* Breathing Mechanism */
  {"sk":"breathing","type":"mc","q":"What muscle controls breathing by moving up and down?","o":["The diaphragm","The biceps","The heart","The stomach"],"a":0,"fb":"The <b>diaphragm</b> is a dome-shaped muscle that controls breathing.","hint":"It's a big dome under the lungs."},
  {"sk":"breathing","type":"mc","q":"When you inhale (breathe in), the diaphragm ___ .","o":["moves down and flattens","moves up","stays still","pushes the heart"],"a":0,"fb":"On <b>inhalation the diaphragm flattens (moves down)</b>, making more space so air rushes in.","hint":"More space = air comes in."},
  {"sk":"breathing","type":"mc","q":"When you exhale (breathe out), air is pushed out because the diaphragm ___ .","o":["moves up (relaxes)","moves down","disappears","blocks the nose"],"a":0,"fb":"On <b>exhalation the diaphragm relaxes and moves up</b>, squeezing air out.","hint":"Less space = air goes out."},
  {"sk":"breathing","type":"fill","q":"The dome-shaped muscle below the lungs that controls breathing is the ___.","a":"diaphragm","fb":"The <b>diaphragm</b> controls breathing by moving up and down.","hint":"Starts with 'dia'."},
  {"sk":"breathing","type":"mc","q":"Which ribs and muscles also help expand the chest when you breathe?","o":["Intercostal muscles between the ribs","Leg muscles","Arm muscles","Finger muscles"],"a":0,"fb":"The <b>intercostal muscles</b> between the ribs help expand and contract the chest.","hint":"They live between the ribs."},
  /* Gas Exchange in Lungs */
  {"sk":"gas-exchange","type":"mc","q":"Where does gas exchange happen in the lungs?","o":["In the alveoli","In the nose","In the trachea","In the ribs"],"a":0,"fb":"Gas exchange happens in the <b>alveoli</b> — tiny air sacs surrounded by blood capillaries.","hint":"Tiny balloons covered in tiny blood vessels."},
  {"sk":"gas-exchange","type":"mc","q":"During gas exchange, oxygen moves from the alveoli into the ___ .","o":["blood","stomach","brain","bones"],"a":0,"fb":"Oxygen passes from the alveoli into the <b>blood</b>, and CO₂ moves from blood into alveoli.","hint":"Blood is the delivery truck."},
  {"sk":"gas-exchange","type":"mc","q":"What gas moves FROM the blood INTO the alveoli to be breathed out?","o":["Carbon dioxide","Oxygen","Nitrogen","Helium"],"a":0,"fb":"<b>Carbon dioxide</b> (a waste product) moves from blood into alveoli and you breathe it out.","hint":"The waste gas your cells produce."},
  {"sk":"gas-exchange","type":"fill","q":"Tiny air sacs in the lungs where gas exchange occurs are called ___.","a":"alveoli","fb":"<b>Alveoli</b> are the tiny air sacs where oxygen and CO₂ are exchanged.","hint":"Singular: alveolus."},
  {"sk":"gas-exchange","type":"mc","q":"Why do the alveoli have thin walls and many capillaries?","o":["So gases can pass easily into the blood","To make the lungs heavy","To store food","To protect the heart"],"a":0,"fb":"<b>Thin walls + lots of capillaries</b> make gas exchange fast and easy.","hint":"Thin + many = efficient."},
  /* Respiratory Care */
  {"sk":"resp-care","type":"mc","q":"Which habit helps keep your respiratory system healthy?","o":["Exercising regularly","Smoking","Breathing polluted air","Never moving"],"a":0,"fb":"<b>Regular exercise</b> strengthens your lungs and heart.","hint":"Healthy body = healthy lungs."},
  {"sk":"resp-care","type":"mc","q":"Why is smoking harmful to the respiratory system?","o":["It damages the lungs and alveoli","It makes you taller","It helps you breathe","It cleans the nose"],"a":0,"fb":"Smoking <b>damages the lungs and alveoli</b>, making breathing hard.","hint":"It hurts the tiny air sacs."},
  {"sk":"resp-care","type":"mc","q":"What should you do to avoid spreading germs when you cough?","o":["Cover your mouth and nose","Shout loudly","Hold your breath","Run away fast"],"a":0,"fb":"<b>Cover your mouth/nose</b> when coughing to avoid spreading germs.","hint":"Protect others, protect yourself."},
  {"sk":"resp-care","type":"fill","q":"Breathing clean air, exercising and avoiding smoke are ways to ___ for your respiratory system.","a":"care","fb":"These habits show you <b>care for</b> your respiratory system.","hint":"Taking good care of your lungs."},
  {"sk":"resp-care","type":"mc","q":"What is the biblical reason to care for your body?","o":["Your body is a temple of the Holy Spirit (1 Cor 6:19)","It makes you popular","So you can run faster","No reason at all"],"a":0,"fb":"The Bible says your body is a <b>temple of the Holy Spirit</b> — we care for it to honor God.","hint":"Psalm 150:6 says everything that breathes should praise the LORD."},
  /* Respiratory Vocabulary */
  {"sk":"resp-vocab","type":"mc","q":"Which word means 'to breathe in'?","o":["Inhale","Exhale","Digest","Absorb"],"a":0,"fb":"<b>Inhale</b> = breathe in. <b>Exhale</b> = breathe out.","hint":"'In' is inside the word."},
  {"sk":"resp-vocab","type":"mc","q":"The word 'alveoli' refers to ___ .","o":["tiny air sacs in the lungs","stomach muscles","nose hairs","bone cells"],"a":0,"fb":"<b>Alveoli</b> = tiny air sacs where gas exchange happens.","hint":"They look like tiny balloons."},
  {"sk":"resp-vocab","type":"mc","q":"What is the scientific name for 'windpipe'?","o":["Trachea","Esophagus","Pharynx","Aorta"],"a":0,"fb":"The windpipe is the <b>trachea</b>.","hint":"Starts with 'tra'."},
  {"sk":"resp-vocab","type":"fill","q":"The word that means 'to breathe out' is ___.","a":"exhale","fb":"<b>Exhale</b> = breathe out.","hint":"The opposite of inhale."},
  {"sk":"resp-vocab","type":"mc","q":"Which gas do humans breathe IN and plants release?","o":["Oxygen","Carbon dioxide","Methane","Smoke"],"a":0,"fb":"We breathe in <b>oxygen</b> — the same gas plants release during photosynthesis!","hint":"We are connected to plants!"},
  /* ===== NEW QUESTION TYPES (Reading) ===== */
  {"sk":"photo-process","type":"tf","q":"Photosynthesis happens only in the roots of a plant.","a":1,"fb":"False — photosynthesis happens mainly in the <b>leaves</b>, where chlorophyll captures sunlight.","hint":"Where is the green pigment?","skillType":"R"},
  {"sk":"plant-resp","type":"tf","q":"Plants respire all the time, day and night.","a":0,"fb":"True — plants always need energy, so they respire all the time.","hint":"Do living things ever stop needing energy?","skillType":"R"},
  {"sk":"human-organs","type":"tf","q":"The trachea carries food to the stomach.","a":1,"fb":"False — the <b>trachea</b> (windpipe) carries air to the lungs; the esophagus carries food.","hint":"Air tube or food tube?","skillType":"R"},
  {"sk":"resp-care","type":"tf","q":"Smoking is good for your lungs.","a":1,"fb":"False — smoking damages the lungs and alveoli.","hint":"Does smoke help or hurt?","skillType":"R"},
  {"sk":"gas-exchange","type":"tf","q":"Oxygen passes from the alveoli into the blood.","a":0,"fb":"True — that is exactly how oxygen reaches your blood.","hint":"Direction of oxygen: air sacs → blood.","skillType":"R"},
  {"sk":"photo-inputs","type":"tf","q":"Water is one of the inputs of photosynthesis.","a":0,"fb":"True — roots absorb water from the soil; it is an input.","hint":"Three inputs: sunlight, water, CO₂.","skillType":"R"},
  /* ===== NEW: ORDER (sequencing) ===== */
  {"sk":"photo-process","type":"order","q":"Put the photosynthesis steps in the correct order.","steps":["Sunlight hits the leaves","Roots absorb water from the soil","Leaves take in carbon dioxide","Glucose and oxygen are made"],"fb":"Sunlight + water + CO₂ → glucose + oxygen in the leaves.","skillType":"R"},
  {"sk":"breathing","type":"order","q":"Order the path of air when you breathe in.","steps":["Nose (air is warmed and cleaned)","Trachea (windpipe)","Bronchi","Lungs (alveoli)"],"fb":"Air goes: nose → trachea → bronchi → lungs.","skillType":"R"},
  {"sk":"gas-exchange","type":"order","q":"Order what happens during gas exchange.","steps":["Oxygen enters the alveoli","Oxygen passes into the blood","Carbon dioxide leaves the blood","You breathe the CO₂ out"],"fb":"O₂ in, CO₂ out — across the thin alveoli walls.","skillType":"R"},
  {"sk":"root-resp","type":"order","q":"Order why over-watering hurts plants.","steps":["Water fills the soil air spaces","Roots cannot get oxygen","Roots cannot respire for energy","The roots may rot"],"fb":"Too much water = no air for the roots.","skillType":"R"},
  /* ===== NEW: LISTENING (TTS) ===== */
  {"sk":"photo-inputs","type":"listen","audio":"Plants need sunlight, water and carbon dioxide to make their own food.","q":"You heard: what do plants need to make food?","o":["Sunlight, water and CO₂","Sugar, salt and air","Oxygen, soil and fire","Milk, bread and water"],"a":0,"fb":"Plants need sunlight, water and carbon dioxide.","skillType":"L"},
  {"sk":"breathing","type":"listen","audio":"When you breathe in, the diaphragm moves down and flattens, and air rushes into your lungs.","q":"You heard: what does the diaphragm do when you inhale?","o":["It moves down and flattens","It moves up","It disappears","It closes the nose"],"a":0,"fb":"On inhalation the diaphragm flattens (moves down).","skillType":"L"},
  {"sk":"human-organs","type":"listen","audio":"The path of air is nose, trachea, bronchi and lungs.","q":"You heard: what comes after the trachea?","o":["Bronchi","Nose","Alveoli only","Stomach"],"a":0,"fb":"Air goes nose → trachea → bronchi → lungs.","skillType":"L"},
  {"sk":"plant-resp","type":"listen","audio":"Respiration releases energy from glucose using oxygen, and it happens all the time.","q":"You heard: what does respiration release?","o":["Energy","Water","Color","Sound"],"a":0,"fb":"Respiration releases energy from glucose.","skillType":"L"},
  /* ===== NEW: SPEAKING (TTS model + self-assess) ===== */
  {"sk":"resp-vocab","type":"speak","word":"oxygen","q":"Say the word 'oxygen'. Listen, repeat out loud and rate yourself.","o":["🗣️ I said it!","🔁 Let me listen again"],"a":0,"fb":"Great — keep practicing the word 'oxygen'!","skillType":"S"},
  {"sk":"resp-vocab","type":"speak","word":"photosynthesis","q":"Say the word 'photosynthesis'. Listen, repeat out loud and rate yourself.","o":["🗣️ I said it!","🔁 Let me listen again"],"a":0,"fb":"Nice! 'Photosynthesis' is a long word — great job!","skillType":"S"},
  {"sk":"resp-vocab","type":"speak","word":"diaphragm","q":"Say the word 'diaphragm'. Listen, repeat out loud and rate yourself.","o":["🗣️ I said it!","🔁 Let me listen again"],"a":0,"fb":"Excellent! The diaphragm is the breathing muscle.","skillType":"S"},
  {"sk":"resp-vocab","type":"speak","word":"alveoli","q":"Say the word 'alveoli'. Listen, repeat out loud and rate yourself.","o":["🗣️ I said it!","🔁 Let me listen again"],"a":0,"fb":"Perfect — alveoli are the tiny air sacs!","skillType":"S"}

];
